# Generated by Django 3.0.7 on 2020-06-18 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('remain', models.DecimalField(decimal_places=2, max_digits=20)),
                ('open_date', models.DateField()),
                ('account_type', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('asset', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('depart_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('depart_name', models.CharField(max_length=20)),
                ('depart_type', models.CharField(blank=True, max_length=15)),
                ('manager', models.CharField(max_length=18)),
                ('bank_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banksys.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('state', models.CharField(default='0', max_length=1)),
                ('bank_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banksys.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='CheckAcc',
            fields=[
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='banksys.Account')),
                ('overdraft', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='SaveAcc',
            fields=[
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='banksys.Account')),
                ('interest_rate', models.FloatField(blank=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_phone', models.CharField(blank=True, max_length=11)),
                ('emp_addr', models.CharField(blank=True, max_length=50)),
                ('emp_type', models.BooleanField(max_length=1)),
                ('emp_start', models.DateField()),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banksys.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=10)),
                ('client_phone', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('contact_phone', models.CharField(max_length=11)),
                ('contact_name', models.CharField(max_length=10)),
                ('contact_email', models.EmailField(blank=True, max_length=30)),
                ('relation', models.CharField(max_length=10)),
                ('acc_res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_res', to='banksys.Employee')),
                ('loan_res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_res', to='banksys.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pay_date', models.DateField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banksys.Client')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banksys.Loan')),
            ],
            options={
                'unique_together': {('loan_id', 'client_id', 'pay_amount', 'pay_date')},
            },
        ),
        migrations.CreateModel(
            name='ClientLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banksys.Client')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banksys.Loan')),
            ],
            options={
                'unique_together': {('loan_id', 'client_id')},
            },
        ),
        migrations.CreateModel(
            name='ClientAcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_access', models.DateField()),
                ('account_type', models.CharField(max_length=5)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banksys.Account')),
                ('bank_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banksys.Bank')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banksys.Client')),
            ],
            options={
                'unique_together': {('account_id', 'client_id')},
            },
        ),
    ]
