# Generated by Django 3.0.7 on 2020-06-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banksys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkacc',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='clientacc',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='clientacc',
            old_name='bank_name',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='clientacc',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='clientloan',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='clientloan',
            old_name='loan_id',
            new_name='loan',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='bank_name',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='bank_name',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='loan_id',
            new_name='loan',
        ),
        migrations.RenameField(
            model_name='saveacc',
            old_name='account_id',
            new_name='account',
        ),
        migrations.AlterUniqueTogether(
            name='clientacc',
            unique_together={('account', 'client')},
        ),
        migrations.AlterUniqueTogether(
            name='clientloan',
            unique_together={('loan', 'client')},
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('loan', 'client', 'pay_amount', 'pay_date')},
        ),
    ]
