# Generated by Django 3.0.7 on 2020-06-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksys', '0002_auto_20200626_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_type',
            field=models.IntegerField(max_length=1),
        ),
    ]
