# Generated by Django 3.0.7 on 2020-06-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksys', '0004_auto_20200626_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
