# Generated by Django 3.0.7 on 2020-06-27 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banksys', '0005_auto_20200626_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='acc_res',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acc_res', to='banksys.Employee'),
        ),
        migrations.AlterField(
            model_name='client',
            name='loan_res',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_res', to='banksys.Employee'),
        ),
    ]
