# Generated by Django 3.0.7 on 2020-06-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksys', '0006_auto_20200627_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
    ]
