# Generated by Django 3.0.7 on 2020-06-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksys', '0008_auto_20200627_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkacc',
            name='overdraft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
