# Generated by Django 3.0.7 on 2020-06-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksys', '0009_auto_20200627_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientacc',
            name='latest_access',
            field=models.DateField(blank=True, null=True),
        ),
    ]
