# Generated by Django 3.0.7 on 2020-06-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksys', '0010_auto_20200627_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='remain',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='checkacc',
            name='overdraft',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_amount',
            field=models.FloatField(),
        ),
    ]
